---
# tasks file for apigee-opdk-portal-silent-installation-config

- name: Construct the portal-silent-install file
  template:
    src: 'portal-silent-install.conf.j2'
    dest: "{{ opdk_portal_installation_config_file }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: provided_response_file is not defined or not provided_response_file
  tags:
  - no-silent-install

- name: Copy provided silent-install file
  copy:
    src: "{{ provided_response_file }}"
    dest: "{{ opdk_installation_config_file }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: provided_response_file is defined and provided_response_file
  tags:
  - no-silent-install
